  - name: Start MySQL container
    docker_container:
      name: mysql
      image: mysql:5.7
      state: started
      restart_policy: always
      env:
        MYSQL_ROOT_PASSWORD: dbwebbDevops
        MYSQL_DATABASE: microblog-db
        MYSQL_USER: microblog-DB_USER
        MYSQL_PASSWORD: dettaervoratpw
      volumes:
        - db_data:/var/lib/mysql
      ports:
        - "3306:3306"

  - name: Start Node exporter
    docker_container:
      name: Node-exporter
      image: prom/node-exporter:v1.2.2
      ports:
        - "9100:9100"
      restart_policy: unless-stopped
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
      command:
        - '--path.procfs=/host/proc'
        - '--path.rootfs=/rootfs'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.mount-points-exclude=^(sys|proc|dev|host|etc)(\s|/)'