---
- name: Start or update Microblog container
  docker_container:
    name: microblog
    image: "{{ docker_image_tag }}"
    state: started
    restart_policy: always
    pull: true
    recreate: yes
    env:
      MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
      MYSQL_DATABASE: "{{ MYSQL_DATABASE }}"
      MYSQL_USER: "{{ MYSQL_USER }}"
      MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
      DATABASE_URL: "mysql+pymysql://{{ MYSQL_USER }}:{{ MYSQL_PASSWORD }}@{{ DATABASE_HOST }}/{{ MYSQL_DATABASE }}"
      DATABASE_HOST: "{{ DATABASE_HOST }}"
    ports:
      - "8000:5000"
  register: container_action

- name: Check if the container is running
  docker_container_info:
    name: microblog
  register: microblog_container