# syntax=docker/dockerfile:1.4
FROM python:3.8-alpine

# Add a build argument for the application version
ARG APP_VERSION=unknown
ENV APP_VERSION=${APP_VERSION}

RUN adduser -D microblog

WORKDIR /home/microblog

COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./

RUN python -m venv .venv && .venv/bin/pip3 install -r requirements.txt

ENV FLASK_APP microblog.py

RUN chmod +x boot.sh && chown -R microblog:microblog ./

USER microblog

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]
