---
- hosts: appserver
  serial: 1  # Uppdatera en server åt gången
  vars:
    ansible_python_interpreter: /usr/bin/python3
    MYSQL_ROOT_PASSWORD: dbwebbDevops
    MYSQL_DATABASE: microblog-db
    MYSQL_USER: microblog-DB_USER
    MYSQL_PASSWORD: dettaervoratpw
    docker_image_tag: jawnta/microblog:v0.2.3  # kan överstyras vid exekvering
    DATABASE_HOST: database.microbloggu.me
  remote_user: deploy
  become: yes
  become_method: sudo
  roles:
    - docker_install
    - appserver