name: Continuous Delivery

on:
  release:
    types: [created]
  
jobs:
  ci:
    uses: ./.github/workflows/main.yml
  dockerpush:
    uses: ./.github/workflows/dockerpush.yml
    needs: ci
    secrets: inherit
  cs:
    uses: ./.github/workflows/cs.yml
    needs: dockerpush

  deploy:
    runs-on: ubuntu-latest
    needs: [ci, dockerpush, cs]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.azure_ssh_key_priv }}

    - name: Extract GitHub Release Tag
      id: extract-tag
      run: echo "RELEASE_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      
    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install ansible -y

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i ./ansible/hosts ./ansible/appserver.yml -e "docker_image_tag=jawnta/microblog:$RELEASE_TAG"

      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
