name: Continuous Delivery

on:
  release:
    types: [created]
  
jobs:
  ci:
    uses: ./.github/workflows/main.yml
  dockerpush:
    uses: ./.github/workflows/dockerpush.yml
    needs: ci
    secrets: inherit
    outputs:
      docker_image_tag: ${{ steps.meta.outputs.tags }}
  cs:
    uses: ./.github/workflows/cs.yml
    needs: dockerpush

  deploy:
    runs-on: ubuntu-latest
    needs: [ci, dockerpush, cs]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.azure_ssh_key_priv }}

    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install ansible -y

    # - name: Run Ansible Playbook
    #   run: |
    #     ansible-playbook -i ./ansible/hosts ./ansible/appserver.yml -e "docker_image_tag=${{ steps.meta.outputs.tags }}"
    - name: Run Ansible Playbook
      run: ansible-playbook -i ./ansible/hosts ./ansible/appserver.yml -e "docker_image_tag=${{ needs.dockerpush.outputs.docker_image_tag }}"

      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
