name: Continuous Delivery

on:
  workflow_run:
    workflows: ["Continuous Integration", "Run security tests"]
    types: 
      - completed
    branches: [ main ]
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: jawnta/microblog

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.azure_ssh_key_priv }}

    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install ansible -y

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i ./ansible/hosts ./ansible/appserver.yml -e "docker_image_tag=${{ steps.meta.outputs.tags }}"
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
