- name: Install Docker and pip3
  apt:
    name:
      - docker.io
      - python3-pip
    state: present
    update_cache: yes

- name: Install Docker SDK for Python
  pip:
    name: docker
    executable: pip3
